# -*- coding: utf-8 -*-
"""CHAT BOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_ZCIA1EJzRdkeRa8UWm1otdePADGrmO
"""

def advanced_chatbot():
  print("Hello! I am an advanced chatbot. Type 'quit' to exit.")
  while True:
    user_input = input("You: ").lower()
    if user_input == "quit":
      print("Chatbot: Goodbye! It was nice chatting with you.")
      break
    elif "hello" in user_input or "hi" in user_input:
      print("Chatbot: Hello there! How can I assist you today?")
    elif "how are you" in user_input:
      print("Chatbot: I'm doing great, thank you for asking!")
    elif "name" in user_input:
      print("Chatbot: I am a chatbot created to help you.")
    else:
      print(f"Chatbot: I received your message: '{user_input}'. Is there anything else?")

advanced_chatbot()

