# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r7-TLySYvpcnVkqDl4Z3MGJ_8ZTlveOg
"""

def laptop_expert(turns_on, internet_works, is_slow):

    if turns_on == "no":
        return "Check the charger and power cable."

    elif internet_works == "no":
        return "Check Wi-Fi and restart the router."

    elif is_slow == "yes":
        return "Close unused programs and restart the laptop."

    else:
        return "The system does not find a common problem."


turns_on = input("Does the laptop turn on? yes/no: ").lower()
internet_works = input("Does the internet work? yes/no: ").lower()
is_slow = input("Is the laptop slow? yes/no: ").lower()

advice = laptop_expert(turns_on, internet_works, is_slow)

print("\n--- Expert System Advice ---")
print(advice)